AWSTemplateFormatVersion: 2010-09-09

Description: Deploy a PyTorch model to SageMaker for Dev/QA Testing

Parameters:

  ImageRepoName:
    Type: String
    Description: Name of the model image ECR (Docker) repo.
    
  ImageTagName:
    Type: String
    Description: Name of the model image ECR (Docker) tag.

  ModelName:
    Type: String
    Description: Name of the PyTorch model.
    
  RoleName:
    Type: String
    Description: Name of the Pipeline execution Role.
    Default: MLOps-pytorch

  TrainJobId:
    Type: String
    Description: Id of the Codepipeline + SagemakerJobs.

  EndpointInstanceCount:
    Type: Number
    Description: Number of instances to launch for the endpoint.
    MinValue: 1

  EndpointInstanceType:
    Type: String
    Description: The ML compute instance type for the endpoint.
    
Resources:

  Model:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub mlops-${ModelName}-${TrainJobId}
      PrimaryContainer:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepoName}:${ImageTagName}
        ModelDataUrl: !Sub s3://mlops-pytorch-${AWS::Region}-${AWS::AccountId}/${TrainJobId}/mlops-${ModelName}-${TrainJobId}/output/model.tar.gz
        Environment:
          SAGEMAKER_PROGRAM: app.py
          SAGEMAKER_SUBMIT_DIRECTORY: /opt/ml/model/code
          SAGEMAKER_CONTAINER_LOG_LEVEL: 20
          MMS_DEFAULT_WORKERS_PER_MODEL: "1"
          TORCH_HOME: "/opt/ml/model"
          PIPELINE_BUCKET: !Sub mlops-pytorch-${AWS::Region}-${AWS::AccountId}
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${RoleName}
  
  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
      - InitialInstanceCount: !Ref EndpointInstanceCount
        InitialVariantWeight: 1.0
        InstanceType: !Ref EndpointInstanceType
        ModelName: !GetAtt Model.ModelName
        VariantName: AllTraffic
    DependsOn: Model

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub ${ModelName}-dev-endpoint
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
    DependsOn: EndpointConfig